### ISSUE TITLE
Where is data from Marmotte?

### ISSUE THREAD

**Issue by LarryDong** [norlab-ulaval/Norlab_wiki#2]
Hi,

Thanks for sharing this dataset.  
That's great and we're very interested in this dataset.

I notice that this dataset description is 
> The RTS-GT dataset was taken with **two** different robotic platform and contains over 49 kilometers of prism trajectories tracked by three RTSs.

But in the wiki page [RTS‐GT Dataset 2023](https://github.com/norlab-ulaval/Norlab_wiki/wiki/RTS%E2%80%90GT-Dataset-2023),  
all deployments are Warthog or HD2 (what's HD? Handhold?)  
So any dataset recorded by Marmotte is released now?

Thanks.

**Comment by pomerlef** [comment]
Marmotte is the HD2 (Heavy Duty 2) from SuperDroid.

@vdsmax It would be worth it to modify the doc to clarify.

**Comment by LarryDong** [comment]
Thanks.
